//---------Test for Authentication---------
post http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name" : "Wasir Huzaifa",
    "email" : "wasir@gmail.com",
    "password" : "1234" 
}
###

post http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "wasir@gmail.com",
    "password" : "1234"
}
###

//---------Test for League---------
post http://localhost:3000/league
Content-Type: application/json

{
    "name" : "BPL",
    "type" : "public",
    "created_by" : 1,
    "start_date" : "2025-03-01",
    "last_date" : "2025-06-15"
}

###
get http://localhost:3000/api/league

###
get http://localhost:3000/league/1
###

//---------Test for Real Team---------
post http://localhost:3000/api/team
Content-Type: application/json

{
    "name" : "Lunatic-Six",
    "country" : "Bangladesh",
    "league_id" : 1
}
###
get http://localhost:3000/api/team
###

//---------Test for Player---------
POST http://localhost:3000/api/player
Content-Type: application/json

{
  "name": "kane williamson",
  "role": "batsman",
  "real_team_id": 1,
  "nationality": "new zealand",
  "price": 950000
}
###
GET http://localhost:3000/api/player/1
###

//---------Test for Fantasy Team---------
post http://localhost:3000/api/fantasyteam
Content-Type: application/json

{
    "user_id" : 1,
    "league_id" : 1,
    "team_name" : "Iron Fist"
}
###

get http://localhost:3000/api/fantasyteam
###

//---------Test for Fantasy Team Player---------
post http://localhost:3000/api/fantasyteamplayer
Content-Type: application/json

{
    "fantasy_team_id": 1,
    "player_id": 1,
    "is_captain": true,
    "is_vice_captain": false
}
###

get http://localhost:3000/api/fantasyteamplayer/1
###

//---------Test for Venue---------
post http://localhost:3000/api/venue
Content-Type:  application/json

{
    "name": "Eden Gardens",
    "city": "Kolkata",
    "country": "India",
    "capacity": 68000
}
###
get http://localhost:3000/api/venue
###

//---------Test for Matches---------
post http://localhost:3000/api/match
Content-Type: application/json

{
    "home_team_id": 1,
    "away_team_id": 2,
    "match_date": "2025-03-15",
    "venue_id": 1,
    "league_id": 1
}
###
get http://localhost:3000/api/match
###

//---------Test for PlayerStats---------
post http://localhost:3000/api/playerstats
Content-Type: application/json

{
    "player_id": 1,
    "match_id": 1,
    "runs": 50,
    "wickets": 2,
    "catches": 1
}
###

get http://localhost:3000/api/playerstats
###


//---------Test for Batting Stats---------
post http://localhost:3000/api/battingstats
Content-Type: application/json

{
    "player_id": 1,
    "match_id": 1,
    "runs": 50,
    "balls": 40,
    "fours": 4,
    "sixes": 2,
    "strike_rate": 125
}
###

get http://localhost:3000/api/battingstats
###

//---------Test for Bowling Stats---------

post http://localhost:3000/api/bowlingstats
Content-Type: application/json

{
    "player_id": 1,
    "match_id": 1,
    "overs": 8,
    "runs_given": 45,
    "wickets": 3,
    "economy": 5.62
}
###

get http://localhost:3000/api/bowlingstats
###

//---------Test for Fielding Stats---------

post http://localhost:3000/api/fieldingstats
Content-Type: application/json

{
    "player_id": 1,
    "match_id": 1,
    "catches": 2,
    "run_outs": 1,
    "stumpings": 0
}
###

get http://localhost:3000/api/fieldingstats
###


//---------Test for Weeks---------
post http://localhost:3000/api/week
Content-Type: application/json

{
  "start_date": "2025-10-14",
  "end_date": "2025-10-20"
}
### 

get http://localhost:3000/api/week
###

//---------Test for Fixtures---------
post http://localhost:3000/api/fixture
Content-Type: application/json

{
  "match_id": 1,
  "week_id": 1,
  "status": "scheduled"
}
###

get http://localhost:3000/api/fixture
###

//---------Test for Transaction---------
post http://localhost:3000/api/transaction
Content-Type: application/json

{
    "user_id": 1,
    "amount": 500,
    "type": "deposit",
    "date": "2025-10-12",
    "status": "completed"
}
###

get http://localhost:3000/api/transaction
###



//---------Test for Wallet---------
post http://localhost:3000/api/wallet
Content-Type: application/json

{
  "user_id": 1,
  "balance": 1000
}
###

get http://localhost:3000/api/wallet
###

//---------Test for deposit---------

post http://localhost:3000/api/deposit
Content-Type: application/json

{
    "wallet_id": 1,
    "amount": 5000,
    "method": "bonus",
    "date": "2025-10-12"
}
###

get http://localhost:3000/api/deposit
###


//---------Test for Fantasy Private Leagues---------
post http://localhost:3000/api/fantasy-private-league
Content-Type: application/json

{
    "name": "Super League",
    "created_by": 1,
    "invite_code": "1234",
    "max_users": 10
}

###

get http://localhost:3000/api/fantasy-private-league
###

//---------Test for Fantasy Private League Members---------

post http://localhost:3000/api/fantasy-private-league-member/join
Content-Type: application/json

{
    "private_league_id": 1,
    "user_id": 2
}
###

get http://localhost:3000/api/fantasy-private-league-member/1/members
###